"""Prompts for generating interview prep roadmap infographic."""


def build_infographic_prompt(plan: dict) -> str:
    overview = plan.get("overview", {}) or {}
    role = overview.get("role", "Candidate")
    seniority = overview.get("seniority", "").title() or ""
    title = f"Interview Prep Summary for {seniority} {role}".strip()

    bullets = plan.get("summary_plan", []) or []
    if not bullets and plan.get("days"):
        bullets = [
            f"Day {i+1}: {d.get('title', 'Focus')}"
            for i, d in enumerate(plan["days"][:7])
        ]

    prep_steps = "\n".join(f"{i+1}. {b}" for i, b in enumerate(bullets))
    print(prep_steps)
    return f"""
    Design a clean, minimalist infographic poster titled "{title}".
    Description for each day:
    {prep_steps}
    Use exact description for each day as given above.
    Leave some white space on the bottom for a footer and or additional info.
    
    Layout: poster title, preparation info for 7 days in 
    rows stacked top-to-bottom: rows 1 to 7 = Day 1..Day 7,
    and white space for an ad-hoc footer or additional prep step.

    Typography:
    - Each row should have: on a left a small flat icon;
    next to it = headline (“Day N”), below headline add description.

    Styling:
    - Pastel palette, modern flat design, ample whitespace.
    - Consistent icon style.
    """


def build_infographic_prompt_complex(plan: dict) -> str:
    overview = plan.get("overview", {}) or {}
    role = overview.get("role", "Candidate")
    seniority = overview.get("seniority", "").title() or ""
    title = f"Roadmap of {seniority} {role} Interview Prep".strip()
    print(plan)
    bullets = plan.get("summary_plan", []) or []
    if not bullets and plan.get("days"):
        bullets = [
            f"Day {i+1}: {d.get('title', 'Focus')}"
            for i, d in enumerate(plan["days"][:7])
        ]

    prep_steps = "\n".join(f"{i+1}. {b}" for i, b in enumerate(bullets))
    print(prep_steps)
    return f"""
    Design a clean, minimalist infographic poster titled "{title}".
    Description for each day:
    {prep_steps}
    Use exact description for each day as given above.
    Leave some space on the bottom for a small footer: "Generated by AI".
    
    Layout: below poster title, add preparation info for 7 days in 
    rows stacked top-to-bottom: rows 1 to 7 = Day 1..Day 7.

    Typography & sizing:
    - Besides title, each row should have: on a left a small flat icon;
    next to it = headline (“Day N”), below headline add description.
    - Font sizes: poster title 18-20pt, headline 14-16pt, description 10-12pt.
    If needed reduce font size to fit descriptions for all 7 days.

    Styling:
    - Pastel palette, modern flat design, ample whitespace.
    - Consistent icon style. No watermarks or logos. 
    """
